### ISSUE TITLE
Distance Calculation Function

### ISSUE THREAD

**Issue by sidmsmith** [toggledbits/lexpjs#7]
I would like to measure the distance between 2 latitudes and longitudes for a simple expression that I am creating.  I was unable to find any Reactor function for distance so I was going to create my own expression.  The function is defined below:

acos(sin(Radians(Lat1))*sin(Radians(Lat2))+cos(Radians(Lat1))*cos(Radians(Lat2))*cos(Radians(Long2)-Radians(Long1)))*6371/1.6
Note: (the 1.6 results in miles and without results in km)

The issue that I have is that Reactor does not currently support "acos" and "radians".  I created an expression for radians which is pi/180.  Reactor didn't have "pi" so I created a simple expression for it = 22/7.  However, I was unable to find a simple calculation to recreate the "acos" function.

Thus, in order of priority, I'd like to request the following functions:
1. acos - This is the limiting factor at the moment and can not proceed.
2. radians - Would be good to have something available.
3. pi - Low priority but would be good to have something available.
4. distance function - none of the above would be required ;)  if done, would be good to offer results in miles and kilometers/meters if possible.

**Comment by toggledbits** [comment]
OK. This isn't really the right place to ask a question like this; although it's related to the expression language, if I were to make changes here, it would not change anything in Reactor. I would have to also separately update Reactor with the new *lexpjs* to expose the new functions, so the way I think about it (and the way you want to use it), it's more of a Reactor question.. Reactor also has functions that *lexpjs* does not. I provide support for Reactor through the [SmartHome Community](https://smarthome.community/). Make yourself an account there, read the posting guidelines for the Multi-System Reactor category, and post questions/requests there, please.

That said...
* `acos` - I will address it for a future build (soon).
* `radians` - too trivial... multiply by pi over 180
* `pi` - future build
* distance function -- too specialized for the general-purpose library, but once you have the above, you'll have it youself.
